In [1]:
import numpy as np
import pandas as pd

In [2]:
original_data=pd.read_csv('conveyer belt data.csv')

In [3]:
original_data.head()

belt speed m/s  Motor temperature ℃  Motor current A  Drum temperature ℃  \
0            4.30                 52.4            255.4                61.4   
1            3.11                 52.2            234.8                59.6   
2            3.22                 51.6            210.4                59.6   
3            4.23                 52.2            266.2                58.5   
4            4.27                 52.6            284.6                57.5   

   Belt tension MP BELT RUNNIG STATUS  
0               22        broken belt  
1               13               skid  
2               14          off track  
3               24        broken belt  
4               22        broken belt

In [4]:
original_data.columns

Index(['belt speed m/s', 'Motor temperature ℃', 'Motor current A',
       'Drum temperature ℃', 'Belt tension MP', 'BELT RUNNIG STATUS'],
      dtype='object')

In [5]:
# change the column names
new_columns=({'belt speed m/s':'belt speed','Motor temperature ℃':'motor temperature', 
              'Motor current A':'motor current',
              'Drum temperature ℃':'drum temperature', 'Belt tension MP':'belt tension', 
              'BELT RUNNIG STATUS':'belt running status'})

In [6]:
data=original_data.rename(columns=new_columns)

In [7]:
#print the new data set
data.head()

belt speed  motor temperature  motor current  drum temperature  \
0        4.30               52.4          255.4              61.4   
1        3.11               52.2          234.8              59.6   
2        3.22               51.6          210.4              59.6   
3        4.23               52.2          266.2              58.5   
4        4.27               52.6          284.6              57.5   

   belt tension belt running status  
0            22         broken belt  
1            13                skid  
2            14           off track  
3            24         broken belt  
4            22         broken belt

In [8]:
#check the null values
data.isnull().sum()

belt speed             0
motor temperature      0
motor current          0
drum temperature       0
belt tension           0
belt running status    0
dtype: int64

In [9]:
#check the shape
data.shape

(150, 6)

In [10]:
#seperate the independent fetaures and dependent features
X_data=data.iloc[:,:5]

In [11]:
X_data.head()

belt speed  motor temperature  motor current  drum temperature  \
0        4.30               52.4          255.4              61.4   
1        3.11               52.2          234.8              59.6   
2        3.22               51.6          210.4              59.6   
3        4.23               52.2          266.2              58.5   
4        4.27               52.6          284.6              57.5   

   belt tension  
0            22  
1            13  
2            14  
3            24  
4            22

In [12]:
Y_data=data.iloc[:,5:]

In [13]:
Y_data.head()

belt running status
0         broken belt
1                skid
2           off track
3         broken belt
4         broken belt

- the independent features are numerical so we have to consider dependent feature to feature engineering

In [14]:
Y_data.value_counts()

belt running status
broken belt            59
mistracking            37
slip                   19
normal                 16
high temperature       13
skid                    4
brk                     1
off track               1
dtype: int64

In [15]:
# check the unique values
Y_data['belt running status'].unique()

array(['broken belt', 'skid', 'off track', 'high temperature',
       'mistracking', 'normal', 'slip', 'brk'], dtype=object)

In [16]:
from sklearn.preprocessing import LabelEncoder


# Initialize LabelEncoder
label_encoder = LabelEncoder()

y=label_encoder.fit_transform(Y_data['belt running status'])

In [17]:
np.array(data['belt running status'])

array(['broken belt', 'skid', 'off track', 'broken belt', 'broken belt',
       'skid', 'skid', 'broken belt', 'broken belt', 'skid',
       'high temperature', 'broken belt', 'mistracking', 'broken belt',
       'broken belt', 'mistracking', 'broken belt', 'mistracking',
       'normal', 'normal', 'high temperature', 'mistracking',
       'broken belt', 'slip', 'mistracking', 'broken belt', 'broken belt',
       'slip', 'slip', 'broken belt', 'broken belt', 'slip',
       'high temperature', 'broken belt', 'mistracking', 'broken belt',
       'broken belt', 'mistracking', 'broken belt', 'mistracking',
       'normal', 'normal', 'high temperature', 'mistracking',
       'broken belt', 'mistracking', 'broken belt', 'broken belt',
       'mistracking', 'broken belt', 'mistracking', 'normal', 'normal',
       'high temperature', 'mistracking', 'broken belt', 'slip',
       'mistracking', 'broken belt', 'broken belt', 'slip', 'slip',
       'broken belt', 'broken belt', 'slip', 'high tempe

In [18]:
Y_data.value_counts()


belt running status
broken belt            59
mistracking            37
slip                   19
normal                 16
high temperature       13
skid                    4
brk                     1
off track               1
dtype: int64

In [19]:
# now split the data 
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X_data,y,random_state=42,test_size=0.33)

In [20]:
#print the shapes
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(100, 5) (50, 5) (100,) (50,)


In [21]:
#Now scaling the Numerical values
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [22]:
X_data.columns

Index(['belt speed', 'motor temperature', 'motor current', 'drum temperature',
       'belt tension'],
      dtype='object')

In [23]:
numerical_features=['belt speed', 'motor temperature', 'motor current', 'drum temperature','belt tension']
x_train[numerical_features]=sc.fit_transform(x_train[numerical_features])
x_test[numerical_features]=sc.transform(x_test[numerical_features])

In [24]:
x_train.head()

belt speed  motor temperature  motor current  drum temperature  \
96     0.859197          -0.546477      -0.074496          0.000769   
105    0.842445           1.935045      -0.688081          1.385754   
66     0.842445           1.832652      -0.721960          0.000769   
0      0.875949          -0.534431       1.002100          1.385754   
122   -0.162659          -0.540454       2.251856          0.308544   

     belt tension  
96       0.504238  
105     -0.499221  
66      -0.750085  
0        2.009426  
122      3.012884

In [25]:
x_test.head()

belt speed  motor temperature  motor current  drum temperature  \
73     0.725183          -0.522384      -0.718195          1.385754   
18     0.875949          -0.534431      -0.729488          1.385754   
118    0.842445          -0.516361       1.570513          0.000769   
78     0.892700          -0.564546       1.886716         -1.076441   
76    -0.765722          -0.576592      -0.684316          0.847149   

     belt tension  
73       0.002509  
18       0.002509  
118      1.507696  
78       2.762019  
76       0.002509

In [26]:
# import required librarys
import pickle
import pandas as pd
from sklearn.metrics import accuracy_score

In [27]:
# Now use the suiatble machine learning algorithm
# Define the model
from sklearn.linear_model import LogisticRegression

model1=LogisticRegression()

In [28]:
model1.fit(x_train,y_train)

LogisticRegression()

In [30]:
# Make predictions on the test set
test_predictions = model1.predict(x_test)

In [31]:
test_predictions


array([3, 3, 1, 1, 3, 3, 3, 1, 1, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 3, 3, 1,
       3, 1, 3, 1, 3, 1, 3, 1, 3, 3, 1, 1, 1, 3, 3, 1, 1, 1, 1, 1, 1, 1,
       3, 3, 3, 1, 3, 1])

In [32]:
#check the accuracy
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

accuracy = accuracy_score(y_test, test_predictions)

In [33]:
cm=confusion_matrix(y_test,test_predictions)
cm

array([[12,  0,  7,  0,  0,  0],
       [ 5,  0,  4,  0,  0,  0],
       [ 4,  0,  6,  0,  0,  0],
       [ 3,  0,  3,  0,  0,  0],
       [ 1,  0,  0,  0,  0,  0],
       [ 3,  0,  2,  0,  0,  0]], dtype=int64)

In [34]:
report=classification_report(y_test,test_predictions)
print(report)

              precision    recall  f1-score   support

           1       0.43      0.63      0.51        19
           2       0.00      0.00      0.00         9
           3       0.27      0.60      0.37        10
           4       0.00      0.00      0.00         6
           6       0.00      0.00      0.00         1
           7       0.00      0.00      0.00         5

    accuracy                           0.36        50
   macro avg       0.12      0.21      0.15        50
weighted avg       0.22      0.36      0.27        50



C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [39]:
# Save the trained model
with open('model1.pkl', 'wb') as f:
    pickle.dump(model1, f)

# Save the standard scaler
with open('sc.pkl', 'wb') as f:
    pickle.dump(sc, f)
    
# Load the saved model
with open('model1.pkl', 'rb') as f:
    loaded_model = pickle.load(f)

# Load the saved scaler
with open('sc.pkl', 'rb') as f:
    loaded_scaler = pickle.load(f)    
    

In [40]:
import numpy as np
new_data=np.array(data.head().iloc[:1,:])

In [41]:
new_data

array([[4.3, 52.4, 255.4, 61.4, 22, 'broken belt']], dtype=object)

In [42]:
new_columns=data.columns.to_list()
new_columns

['belt speed',
 'motor temperature',
 'motor current',
 'drum temperature',
 'belt tension',
 'belt running status']

In [43]:
# convert the data into a data frame
new_data = pd.DataFrame(new_data, columns=new_columns)
new_data

belt speed motor temperature motor current drum temperature belt tension  \
0        4.3              52.4         255.4             61.4           22   

  belt running status  
0         broken belt

In [44]:
new_numerical_features=new_data[['belt speed', 'motor temperature', 'motor current', 'drum temperature','belt tension']]
new_categorical_features=new_data[['belt running status']]

In [45]:
# Standardize numerical features using the loaded scaler
numerical_features_scaled = loaded_scaler.transform(new_numerical_features)

In [46]:
# Make predictions
predictions = loaded_model.predict(numerical_features_scaled)
print("Predictions for new data:")
print(predictions)

Predictions for new data:
[1]


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [47]:
belt_running_status={0:'Break',1:'Broken Belt',2:'High Temperature',3:'Mistracking',4:'Normal',
                    5:'Off track',6:'Skid',7:'Slip'}

In [48]:
belt_running_status=belt_running_status[1]

In [49]:
belt_running_status

'Broken Belt'